name: With Intent
favicon: null
layout_spectrum: 0.7627
typography_spectrum: 0.48415
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9b9b9b'
    - '#cdcdcd'
    - '#5f5f5f'
  brandStrength: 0.25
  lightness: 0.7600639155134559
  saturation: 0.8584936845581979
  rhythmicContrast: 0.75
purpose: []
